/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/public/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Posts Public
         * @description 列出已发布文章（摘要，不含正文）。limit/offset 分页；tag 可选过滤。
         */
        get: operations["list_posts_public_api_public_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post Public */
        get: operations["get_post_public_api_public_posts__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/posts/{slug}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Post Related
         * @description 相关文章：按 tag 交集排序，排除自己，只返回已发布。
         */
        get: operations["get_post_related_api_public_posts__slug__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/inspirations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_public_inspirations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Track */
        post: operations["track_api_public_track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/track/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Path Views
         * @description 单篇文章的累计阅读量，供前端文章页展示。
         */
        get: operations["path_views_api_public_track_views_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/track/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Post Heat
         * @description 各文章累计阅读量（热度降序），供前端列表页画热力条。
         */
        get: operations["post_heat_api_public_track_top_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/pi/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_public_pi_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_public_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Vitals */
        post: operations["report_vitals_api_public_vitals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/phrase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Console Phrase
         * @description 返回当前生效的声纹口令（前端展示用）。公开。
         */
        get: operations["console_phrase_api_console_phrase_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/console/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Console Unlock */
        post: operations["console_unlock_api_console_unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/pi/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["report_api_agent_pi_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 两阶段登录入口。详见 service。
         */
        post: operations["login_api_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Totp Verify
         * @description 登录流第二阶段：拿 step_token + 6 位码换正式 session JWT，同时种 7d 信任 cookie。
         */
        post: operations["totp_verify_api_admin_auth_totp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout-trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Trust
         * @description 清掉本设备的 7d 信任 cookie，下次登录必须 TOTP。
         */
        post: operations["logout_trust_api_admin_auth_logout_trust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/totp/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_admin_auth_totp_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/totp/enroll/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Start */
        post: operations["enroll_start_api_admin_auth_totp_enroll_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/totp/enroll/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Verify */
        post: operations["enroll_verify_api_admin_auth_totp_enroll_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable
         * @description 关闭 TOTP（紧急用，会丢掉信任 cookie）。需要已经登录态。
         */
        post: operations["disable_api_admin_auth_totp_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts Admin */
        get: operations["list_posts_admin_api_admin_posts_get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_api_admin_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Post */
        put: operations["update_post_api_admin_posts__item_id__put"];
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_admin_posts__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/inspirations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_admin_inspirations_get"];
        put?: never;
        /** Create */
        post: operations["create_api_admin_inspirations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/inspirations/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_admin_inspirations__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_admin_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/analytics/top-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top Pages */
        get: operations["top_pages_api_admin_analytics_top_pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/analytics/top-referrers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top Referrers */
        get: operations["top_referrers_api_admin_analytics_top_referrers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/analytics/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Countries */
        get: operations["countries_api_admin_analytics_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/analytics/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_admin_analytics_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seo/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vitals Overview */
        get: operations["vitals_overview_api_admin_seo_vitals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Overview */
        get: operations["search_overview_api_admin_seo_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seo/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keywords */
        get: operations["keywords_api_admin_seo_keywords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seo/indexing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexing */
        get: operations["indexing_api_admin_seo_indexing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/terminal/agent/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Agent */
        post: operations["issue_agent_api_admin_terminal_agent_issue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/terminal/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_admin_terminal_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/terminal/agent/{agent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Agent */
        post: operations["revoke_agent_api_admin_terminal_agent__agent_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/terminal/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_admin_terminal_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Health Check Head */
        head: operations["health_check_head_health_check_head"];
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Agent */
        Agent: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Online */
            online: boolean;
        };
        /** AgentIssueRequest */
        AgentIssueRequest: {
            /** Name */
            name: string;
        };
        /** AgentIssueResponse */
        AgentIssueResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Token */
            token: string;
            /** Base Url */
            base_url: string;
        };
        /**
         * AgentLite
         * @description C 端公开返回的 agent 简版（不含 created_at / revoked_at 等内部字段）。
         */
        AgentLite: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Online */
            online: boolean;
        };
        /** ConsoleUnlockRequest */
        ConsoleUnlockRequest: {
            /**
             * Method
             * @enum {string}
             */
            method: "voice" | "totp";
            /** Voice Transcript */
            voice_transcript?: string | null;
            /** Code */
            code?: string | null;
        };
        /** ConsoleUnlockResponse */
        ConsoleUnlockResponse: {
            /** Term Token */
            term_token: string;
            /** Ttl Seconds */
            ttl_seconds: number;
            /** Agents */
            agents: components["schemas"]["AgentLite"][];
            /** Phrase */
            phrase: string;
        };
        /** CountryStat */
        CountryStat: {
            /** Country */
            country: string;
            /** Pv */
            pv: number;
        };
        /** DailyPoint */
        DailyPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Pv */
            pv: number;
            /** Uv */
            uv: number;
        };
        /** DeviceStats */
        DeviceStats: {
            /** Browsers */
            browsers: components["schemas"]["NameCount"][];
            /** Os */
            os: components["schemas"]["NameCount"][];
            /** Mobile Ratio */
            mobile_ratio: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexingStatus */
        IndexingStatus: {
            /** Url */
            url: string;
            /** Google Indexed */
            google_indexed: boolean;
            /** Bing Indexed */
            bing_indexed: boolean;
            /** Baidu Indexed */
            baidu_indexed: boolean;
            /** Last Checked */
            last_checked: string | null;
        };
        /** Inspiration */
        Inspiration: {
            /** Id */
            id: number;
            /** Content */
            content: string;
            /** Mood */
            mood?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InspirationCreate */
        InspirationCreate: {
            /** Content */
            content: string;
            /** Mood */
            mood?: string | null;
        };
        /** InspirationListPage */
        InspirationListPage: {
            /** Items */
            items: components["schemas"]["Inspiration"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** KeywordStat */
        KeywordStat: {
            /** Query */
            query: string;
            /** Occurrences */
            occurrences: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description 两阶段登录的统一响应。
         *
         *     - `requires_totp = false` → 直接拿 token 即可（未启用 TOTP 或 trust cookie 有效）
         *     - `requires_totp = true`  → 用 step_token 调 /totp/verify 拿正式 token
         */
        LoginResponse: {
            /** Requires Totp */
            requires_totp: boolean;
            /** Token */
            token?: string | null;
            /** Expires In */
            expires_in?: number | null;
            /** Step Token */
            step_token?: string | null;
        };
        /** NameCount */
        NameCount: {
            /** Name */
            name: string;
            /** Pv */
            pv: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Pv Total */
            pv_total: number;
            /** Uv Total */
            uv_total: number;
            /** Pv Today */
            pv_today: number;
            /** Uv Today */
            uv_today: number;
            /** Daily */
            daily: components["schemas"]["DailyPoint"][];
        };
        /** PiHistoryPoint */
        PiHistoryPoint: {
            /** Ts */
            ts: string;
            /** Cpu Temp C */
            cpu_temp_c?: number | null;
            /** Load1 */
            load1?: number | null;
        };
        /**
         * PiReport
         * @description pi-agent 周期上报的一条遥测快照。
         */
        PiReport: {
            /** Hostname */
            hostname: string;
            /** Model */
            model?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
        };
        /**
         * PiStatus
         * @description 前台 /pi 面板用的当前状态。Pi 离线时 online=False，仍返回最后一次快照。
         */
        PiStatus: {
            /** Online */
            online: boolean;
            /** Last Seen */
            last_seen?: string | null;
            /** Age Seconds */
            age_seconds?: number | null;
            /** Hostname */
            hostname?: string | null;
            /** Model */
            model?: string | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            } | null;
            /** History */
            history?: components["schemas"]["PiHistoryPoint"][];
        };
        /** Post */
        Post: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags: string[];
            /** Content */
            content: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /**
         * PostAdminListPage
         * @description admin 列表分页：含正文，编辑时直接取行内 content，无需再请求详情。
         */
        PostAdminListPage: {
            /** Items */
            items: components["schemas"]["Post"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PostCreate */
        PostCreate: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Tags */
            tags?: string[];
            /** Content */
            content: string;
            /** Published At */
            published_at?: string | null;
        };
        /** PostHeat */
        PostHeat: {
            /** Slug */
            slug: string;
            /** Pv */
            pv: number;
        };
        /** PostListPage */
        PostListPage: {
            /** Items */
            items: components["schemas"]["PostSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** PostSummary */
        PostSummary: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Tags */
            tags: string[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** PostUpdate */
        PostUpdate: {
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Content */
            content?: string | null;
            /** Published At */
            published_at?: string | null;
        };
        /** ResponseModel[AgentIssueResponse] */
        ResponseModel_AgentIssueResponse_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["AgentIssueResponse"] | null;
        };
        /** ResponseModel[ConsoleUnlockResponse] */
        ResponseModel_ConsoleUnlockResponse_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["ConsoleUnlockResponse"] | null;
        };
        /** ResponseModel[DeviceStats] */
        ResponseModel_DeviceStats_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["DeviceStats"] | null;
        };
        /** ResponseModel[InspirationListPage] */
        ResponseModel_InspirationListPage_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["InspirationListPage"] | null;
        };
        /** ResponseModel[Inspiration] */
        ResponseModel_Inspiration_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["Inspiration"] | null;
        };
        /** ResponseModel[LoginResponse] */
        ResponseModel_LoginResponse_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["LoginResponse"] | null;
        };
        /** ResponseModel[OverviewResponse] */
        ResponseModel_OverviewResponse_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["OverviewResponse"] | null;
        };
        /** ResponseModel[PiStatus] */
        ResponseModel_PiStatus_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["PiStatus"] | null;
        };
        /** ResponseModel[PostAdminListPage] */
        ResponseModel_PostAdminListPage_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["PostAdminListPage"] | null;
        };
        /** ResponseModel[PostListPage] */
        ResponseModel_PostListPage_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["PostListPage"] | null;
        };
        /** ResponseModel[Post] */
        ResponseModel_Post_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["Post"] | null;
        };
        /** ResponseModel[SearchChannelOverview] */
        ResponseModel_SearchChannelOverview_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["SearchChannelOverview"] | null;
        };
        /** ResponseModel[SearchResponse] */
        ResponseModel_SearchResponse_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["SearchResponse"] | null;
        };
        /** ResponseModel[TotpEnrollStart] */
        ResponseModel_TotpEnrollStart_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["TotpEnrollStart"] | null;
        };
        /** ResponseModel[TotpStatus] */
        ResponseModel_TotpStatus_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["TotpStatus"] | null;
        };
        /** ResponseModel[TotpVerifyResponse] */
        ResponseModel_TotpVerifyResponse_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["TotpVerifyResponse"] | null;
        };
        /** ResponseModel[VitalsOverview] */
        ResponseModel_VitalsOverview_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            data?: components["schemas"]["VitalsOverview"] | null;
        };
        /** ResponseModel[dict] */
        ResponseModel_dict_: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /** ResponseModel[list[Agent]] */
        ResponseModel_list_Agent__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["Agent"][] | null;
        };
        /** ResponseModel[list[CountryStat]] */
        ResponseModel_list_CountryStat__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["CountryStat"][] | null;
        };
        /** ResponseModel[list[IndexingStatus]] */
        ResponseModel_list_IndexingStatus__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["IndexingStatus"][] | null;
        };
        /** ResponseModel[list[KeywordStat]] */
        ResponseModel_list_KeywordStat__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["KeywordStat"][] | null;
        };
        /** ResponseModel[list[PostHeat]] */
        ResponseModel_list_PostHeat__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["PostHeat"][] | null;
        };
        /** ResponseModel[list[PostSummary]] */
        ResponseModel_list_PostSummary__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["PostSummary"][] | null;
        };
        /** ResponseModel[list[TerminalSessionLog]] */
        ResponseModel_list_TerminalSessionLog__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["TerminalSessionLog"][] | null;
        };
        /** ResponseModel[list[TopPage]] */
        ResponseModel_list_TopPage__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["TopPage"][] | null;
        };
        /** ResponseModel[list[TopReferrer]] */
        ResponseModel_list_TopReferrer__: {
            /**
             * Code
             * @default 0
             */
            code: number;
            /**
             * Message
             * @default ok
             */
            message: string;
            /** Data */
            data?: components["schemas"]["TopReferrer"][] | null;
        };
        /** SearchChannelOverview */
        SearchChannelOverview: {
            /** Channel */
            channel: string;
            /** Snapshot Date */
            snapshot_date: string | null;
            /** Impressions Total */
            impressions_total: number;
            /** Clicks Total */
            clicks_total: number;
            /** Ctr Avg */
            ctr_avg: number;
            /** Position Avg */
            position_avg: number;
            /** Indexed Count */
            indexed_count: number;
            /** Top Urls */
            top_urls: components["schemas"]["SearchUrlStat"][];
        };
        /** SearchHit */
        SearchHit: {
            /** Type */
            type: string;
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Timestamp */
            timestamp?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Took Ms */
            took_ms: number;
            /** Total */
            total: number;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /** SearchUrlStat */
        SearchUrlStat: {
            /** Url */
            url: string;
            /** Impressions */
            impressions: number;
            /** Clicks */
            clicks: number;
            /** Ctr */
            ctr: number;
            /** Position */
            position: number;
        };
        /** TerminalSessionLog */
        TerminalSessionLog: {
            /** Id */
            id: number;
            /** Agent Id */
            agent_id: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Bytes In */
            bytes_in: number;
            /** Bytes Out */
            bytes_out: number;
            /** Unlock Method */
            unlock_method: string;
            /** Voice Transcript */
            voice_transcript: string | null;
            /** Client Ip */
            client_ip: string | null;
        };
        /** TopPage */
        TopPage: {
            /** Path */
            path: string;
            /** Pv */
            pv: number;
            /** Uv */
            uv: number;
        };
        /** TopReferrer */
        TopReferrer: {
            /** Referrer */
            referrer: string;
            /** Pv */
            pv: number;
        };
        /** TotpEnrollStart */
        TotpEnrollStart: {
            /** Secret B32 */
            secret_b32: string;
            /** Provisioning Uri */
            provisioning_uri: string;
        };
        /** TotpEnrollVerifyRequest */
        TotpEnrollVerifyRequest: {
            /** Code */
            code: string;
        };
        /** TotpStatus */
        TotpStatus: {
            /** Enrolled */
            enrolled: boolean;
        };
        /** TotpVerifyRequest */
        TotpVerifyRequest: {
            /** Step Token */
            step_token: string;
            /** Code */
            code: string;
        };
        /** TotpVerifyResponse */
        TotpVerifyResponse: {
            /** Token */
            token: string;
            /** Expires In */
            expires_in: number;
        };
        /** TrackRequest */
        TrackRequest: {
            /** Path */
            path: string;
            /** Referrer */
            referrer?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VitalsMetricSummary */
        VitalsMetricSummary: {
            /** Metric */
            metric: string;
            /** P75 */
            p75: number;
            /** P95 */
            p95: number;
            /** Good Ratio */
            good_ratio: number;
            /** Samples */
            samples: number;
        };
        /** VitalsOverview */
        VitalsOverview: {
            /** By Metric */
            by_metric: components["schemas"]["VitalsMetricSummary"][];
            /** Trend */
            trend: components["schemas"]["VitalsTrendPoint"][];
            /** Mobile Ratio */
            mobile_ratio: number;
            /** Samples Total */
            samples_total: number;
        };
        /**
         * VitalsReport
         * @description 前端 web-vitals 包上报的一次指标。
         */
        VitalsReport: {
            /** Path */
            path: string;
            /** Metric */
            metric: string;
            /** Value */
            value: number;
            /** Rating */
            rating: string;
            /** Nav Type */
            nav_type?: string | null;
        };
        /** VitalsTrendPoint */
        VitalsTrendPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** P75 Lcp */
            p75_lcp: number | null;
            /** P75 Cls */
            p75_cls: number | null;
            /** P75 Inp */
            p75_inp: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_posts_public_api_public_posts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description 按 tag 过滤 */
                tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PostListPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_public_api_public_posts__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_Post_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_related_api_public_posts__slug__related_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_PostSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_api_public_inspirations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_InspirationListPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_api_public_track_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    path_views_api_public_track_views_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_heat_api_public_track_top_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_PostHeat__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_public_pi_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PiStatus_"];
                };
            };
        };
    };
    search_api_public_search_get: {
        parameters: {
            query: {
                /** @description 搜索关键词 */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SearchResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_vitals_api_public_vitals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VitalsReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    console_phrase_api_console_phrase_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
        };
    };
    console_unlock_api_console_unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tg_trust?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsoleUnlockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ConsoleUnlockResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_agent_pi_report_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PiReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tg_trust?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    totp_verify_api_admin_auth_totp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_TotpVerifyResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_trust_api_admin_auth_logout_trust_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
        };
    };
    status_api_admin_auth_totp_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_TotpStatus_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_start_api_admin_auth_totp_enroll_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_TotpEnrollStart_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_verify_api_admin_auth_totp_enroll_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpEnrollVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_api_admin_auth_totp_disable_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_admin_api_admin_posts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PostAdminListPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_admin_posts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_Post_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_api_admin_posts__item_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_Post_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_admin_posts__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_api_admin_inspirations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_InspirationListPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_admin_inspirations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspirationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_Inspiration_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_admin_inspirations__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_admin_analytics_overview_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_OverviewResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_pages_api_admin_analytics_top_pages_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_TopPage__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_referrers_api_admin_analytics_top_referrers_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_TopReferrer__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    countries_api_admin_analytics_countries_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_CountryStat__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    devices_api_admin_analytics_devices_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_DeviceStats_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vitals_overview_api_admin_seo_vitals_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_VitalsOverview_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_overview_api_admin_seo_search_get: {
        parameters: {
            query?: {
                channel?: string;
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SearchChannelOverview_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keywords_api_admin_seo_keywords_get: {
        parameters: {
            query?: {
                channel?: string;
                days?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_KeywordStat__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexing_api_admin_seo_indexing_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_IndexingStatus__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_agent_api_admin_terminal_agent_issue_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentIssueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_AgentIssueResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_admin_terminal_agents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_Agent__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_agent_api_admin_terminal_agent__agent_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_admin_terminal_sessions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_TerminalSessionLog__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_head_health_check_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
